### ISSUE TITLE
XP for /lfg

### ISSUE THREAD

**Issue by IQExotic** [Sector-7-Development-Team/Rainbow-Six-Verification#1]
Make the bot give you XP by using the /lfg command.
Maybe also make it give you a XP boost for Voice XP for like 20 mins or so.. What do you think??
You would also have to edit the lfg message too.

**Comment by Dragos-Lion** [comment]
Can be cool but not sure for the voice boost, voice XP is already pretty OP and some could use /lfg while in voc but not playing R6. Some XP at each lfg could be great but what edit do you want me to od on the message ?

**Comment by IQExotic** [comment]
I just meant to say that in the message that will get send so the Gaming Channel every 20 so that people know they will get XP when they use the command. But you think we should add the lfg function with XP and a cooldown for the XP so people cant farm unlimited XP.

**Comment by Dragos-Lion** [comment]
For the XP cooldown, it can be like one LFG XP per day, so I reset the list with the update rank tasks loop.
If you're okay, how much XP with /lfg ?
Okay for the message to edit. But do we keep the Voice boost idea or not ?

**Comment by IQExotic** [comment]
No the Voice Boost idea is off the table for now. Lets say 100 XP for using the LFG command

**Comment by Dragos-Lion** [comment]
Update 1.1.6 of Community Bot
